---
title: "hw2"
output: pdf_document
date: "2024-10-21"
---

```{r}
#read data
videodata <- read.table("videodata.txt",header =TRUE)
videodata
```

```{r}
#read data
videoMultiple <- read.table("videoMultiple.txt",header = TRUE)
videoMultiple
```

1. 
```{r}
#find the point estimator
point_estimate_fraction <- sum(videodata$time >0) / length(videodata$time)

confidence_level <- 0.95
z <- qnorm((confidence_level+1)/2)

#find proportion standard error
se <- sqrt(point_estimate_fraction * (1-point_estimate_fraction)) / sqrt(length(videodata))

#find lower and upper confidence interval
lower_interval_estimate_fraction <- point_estimate_fraction - 2 * se
lower_interval_estimate_fraction

higher_interval_estimate_fraction <- point_estimate_fraction + 2*se
higher_interval_estimate_fraction
```
37.4% of people play video game in the week prior to the survey.


3. 
```{r}
#find the point estimator
point_estimate_average <- mean(videodata$time)

confidence_leve <- 0.95
z <- qnorm((1+confidence_level)/2)

#get the variance of data
variance <- 1/length(videodata$time) * sum((videodata$time - point_estimate_average)**2)

#find average standard error
se <- sqrt(variance) / sqrt (length(videodata$time))

#lower and upper 95% confidence interval
lower_interval_estimate_average <- point_estimate_average - 2*se
higher_interval_estimate_average <- point_estimate_average + 2*se

lower_interval_estimate_average
higher_interval_estimate_average
```
```{r}

```


